---

- name: Unmount a mounted volume
  ansible.builtin.mount:
    path: "{{ efs_data_dir }}"
    state: absent

- name: Remove nfs-common
  ansible.builtin.apt:
    name: 
      - nfs-common
    state: absent