---
dependency:
  name: galaxy
  options:
    collection-file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: ${MOLECULE_DISTRO_NAME:-ubuntu-bionic}
    image: ${MOLECULE_DISTRO_IMAGE:-ubuntu:bionic}

provisioner:
  name: ansible
  log: true
  options:
    vvv: true

verifier:
  name: ansible