---

- name: Verify
  hosts: all

  tasks:
  
    - name: Check nfsstat is installed
      command: "nfsstat --version"
      register: current_version

    - name: Ensure nfsstat is installed
      assert:
        that:
          - current_version.rc == 0